name: Create Release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD_HHmmss
          utcOffset: "+02:00"
      - uses: actions/checkout@v2
      - run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.7

      - name: Build with Maven
        run: mvn install
        env:
          GITHUB_TOKEN: ${{ github.token }}
          TESTCONTAINERS_RYUK_DISABLED: true

      - name: Set Release version env variable
        run: |
          echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Create new release
        uses: marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          automatic_release_tag: ${{ env.RELEASE_VERSION }}
          title: Release ${{ env.RELEASE_VERSION }}
          files: target/cc-light-certificate-generation-service.jar
